/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.awt.EventQueue;

import javax.swing.JFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            JFrame ex = new Snake();
            ex.setVisible(true);
        });
    }
}
