/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.awt.EventQueue;

import javax.swing.JFrame;

public class App {

    public void startGame() {
        EventQueue.invokeLater(() -> {
            JFrame ex = new Snake();
            ex.setVisible(true);
        });
    }

    public static void main(String[] args) {
        App app = new App();
        app.startGame();
    }
}
