/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.graalvm.buildtools.native") version "0.11.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.game.App"
}

graalvmNative {
    toolchainDetection = false
    binaries {
        named("main") {
            mainClass = application.mainClass.get()
            imageName = "snake-game"
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<Exec>("bundleMacApp") {
    group = "distribution"
    description = "Builds a double-clickable macOS .app bundle using jpackage"
    dependsOn("jar")

    val appName = "SnakeGame"
    val packageInputDir = layout.buildDirectory.dir("jpackage/input").get().asFile
    val packageOutputDir = layout.buildDirectory.dir("macos").get().asFile
    val iconWorkDir = layout.buildDirectory.dir("jpackage/icon").get().asFile
    val appIconIcns = iconWorkDir.resolve("SnakeGame.icns")
    val appJar = tasks.named("jar").get().outputs.files.singleFile

    commandLine(
        "jpackage",
        "--type", "app-image",
        "--name", appName,
        "--dest", packageOutputDir.absolutePath,
        "--input", packageInputDir.absolutePath,
        "--main-jar", appJar.name,
        "--main-class", application.mainClass.get(),
        "--icon", appIconIcns.absolutePath,
        "--app-version", "1.0",
        "--vendor", "SnakeGame"
    )

    doFirst {
        val sourcePng = rootProject.file("icon.png")
        if (!sourcePng.exists()) {
            throw GradleException("App icon not found at ${sourcePng.absolutePath}")
        }

        delete(iconWorkDir)
        iconWorkDir.mkdirs()
        val iconSetDir = iconWorkDir.resolve("SnakeGame.iconset")
        iconSetDir.mkdirs()

        fun runCommand(vararg cmd: String) {
            val process = ProcessBuilder(*cmd)
                .inheritIO()
                .start()
            val code = process.waitFor()
            if (code != 0) {
                throw GradleException("Command failed (${code}): ${cmd.joinToString(" ")}")
            }
        }

        // Build required iconset sizes from icon.png without stretching.
        // Resize to fit and then pad to square so non-square source images keep their aspect ratio.
        val iconSizes = listOf(16, 32, 64, 128, 256, 512)
        iconSizes.forEach { size ->
            val normalTemp = iconWorkDir.resolve("tmp_${size}.png")
            runCommand(
                "sips",
                "-Z", size.toString(),
                sourcePng.absolutePath,
                "--out", normalTemp.absolutePath
            )
            runCommand(
                "sips",
                "-p", size.toString(), size.toString(),
                "--padColor", "FFFFFF",
                normalTemp.absolutePath,
                "--out", iconSetDir.resolve("icon_${size}x${size}.png").absolutePath
            )

            val retinaSize = size * 2
            val retinaTemp = iconWorkDir.resolve("tmp_${retinaSize}.png")
            runCommand(
                "sips",
                "-Z", retinaSize.toString(),
                sourcePng.absolutePath,
                "--out", retinaTemp.absolutePath
            )
            runCommand(
                "sips",
                "-p", retinaSize.toString(), retinaSize.toString(),
                "--padColor", "FFFFFF",
                retinaTemp.absolutePath,
                "--out", iconSetDir.resolve("icon_${size}x${size}@2x.png").absolutePath
            )
        }

        runCommand(
            "iconutil",
            "-c", "icns",
            iconSetDir.absolutePath,
            "-o", appIconIcns.absolutePath
        )

        delete(packageInputDir)
        packageInputDir.mkdirs()

        // Copy app jar and runtime dependencies for jpackage input.
        appJar.copyTo(packageInputDir.resolve(appJar.name), overwrite = true)
        configurations.runtimeClasspath.get().files.forEach { dep ->
            dep.copyTo(packageInputDir.resolve(dep.name), overwrite = true)
        }

        delete(packageOutputDir.resolve("${appName}.app"))
    }
}
